version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker-data/mongodb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ~/.docker-data/mongodb-data:/data/db
    ports:
      - 27017:27017
    networks:
      - postgres-db-network

networks:
  postgres-db-network:
    driver: bridge
